import type { ProjectMissionSuggestion } from "./types";

type MissionSeed = Omit<ProjectMissionSuggestion, "projectId">;

const BY_PROJECT: Record<string, MissionSeed[]> = {
  "buildy-clear": [
    {
      id: "bc-sales-page",
      title: "Finaliser la page de vente",
      description: "Structure, copy et CTA pour convertir les visiteurs en clients.",
      impact: 9,
      effort: 4,
      urgency: 9,
      recommended: true,
      reason: "Chemin le plus direct vers un premier revenu.",
      suggestedTasks: ["Revoir le hero et la promesse", "Ajouter preuve sociale", "Tester le CTA principal"],
    },
    {
      id: "bc-offer-clarity",
      title: "Clarifier l'offre",
      description: "Une offre nette : qui, quoi, pourquoi maintenant, à quel prix.",
      impact: 8,
      effort: 3,
      urgency: 8,
      recommended: false,
      reason: "Sans offre claire, la page de vente ne convertira pas.",
    },
    {
      id: "bc-tiktok-video",
      title: "Préparer une vidéo TikTok",
      description: "Un hook court qui montre le problème résolu par Buildy Clear.",
      impact: 6,
      effort: 5,
      urgency: 5,
      recommended: false,
      reason: "Utile après la page de vente, pas avant.",
    },
    {
      id: "bc-testimonial",
      title: "Ajouter preuve / témoignage",
      description: "Collecter ou formuler une preuve crédible pour rassurer.",
      impact: 7,
      effort: 3,
      urgency: 6,
      recommended: false,
      reason: "Renforce la conversion une fois la page en place.",
    },
    {
      id: "bc-funnel-check",
      title: "Vérifier le tunnel",
      description: "Parcours complet : landing → checkout → confirmation.",
      impact: 8,
      effort: 4,
      urgency: 7,
      recommended: false,
      reason: "À faire juste après la page de vente.",
    },
  ],
  "buildy-crafts": [
    {
      id: "bcraft-materials",
      title: "Ajouter matériaux manquants",
      description: "Compléter la base DATA pour les matériaux les plus utilisés.",
      impact: 7,
      effort: 5,
      urgency: 6,
      recommended: false,
      reason: "Débloque des scénarios réalistes en chantier.",
    },
    {
      id: "bcraft-framing",
      title: "Prioriser charpente / ouvertures",
      description: "Stabiliser le module le plus demandé par les utilisateurs cibles.",
      impact: 9,
      effort: 7,
      urgency: 7,
      recommended: true,
      reason: "Impact produit fort sur la crédibilité métier.",
      suggestedTasks: ["Lister les cas charpente", "Valider les règles de calcul", "Tester 2 scénarios"],
    },
    {
      id: "bcraft-data-list",
      title: "Préparer une liste DATA",
      description: "Inventaire des entrées à normaliser pour l'assistant devis.",
      impact: 6,
      effort: 4,
      urgency: 5,
      recommended: false,
      reason: "Fondation pour les prochains corps de métier.",
    },
    {
      id: "bcraft-quote-audit",
      title: "Auditer devis assistant",
      description: "Revue des outputs devis sur 3 chantiers types.",
      impact: 8,
      effort: 5,
      urgency: 6,
      recommended: false,
      reason: "Réduit le risque d'erreurs avant élargissement.",
    },
  ],
  linko: [
    {
      id: "linko-artisan-profile",
      title: "Définir la fiche artisan",
      description: "Structure minimale : services, zone, contact, preuves.",
      impact: 8,
      effort: 4,
      urgency: 5,
      recommended: true,
      reason: "Cœur du produit — sans fiche, pas de valeur.",
    },
    {
      id: "linko-claim-flow",
      title: "Définir le claim flow",
      description: "Comment un artisan revendique et personnalise sa page.",
      impact: 7,
      effort: 5,
      urgency: 4,
      recommended: false,
      reason: "Nécessaire avant acquisition, pas urgent aujourd'hui.",
    },
    {
      id: "linko-pro-acquisition",
      title: "Préparer acquisition pro",
      description: "Liste de 10 artisans cibles et message d'approche.",
      impact: 6,
      effort: 4,
      urgency: 3,
      recommended: false,
      reason: "Projet en pause — à garder pour la reprise.",
    },
  ],
  "1millimetre": [
    {
      id: "1mm-gameplay",
      title: "Améliorer le feeling de gameplay",
      description: "Affiner la sensation de placement et de satisfaction puzzle.",
      impact: 7,
      effort: 6,
      urgency: 3,
      recommended: true,
      reason: "Projet fun — utile seulement si tu veux y revenir.",
    },
    {
      id: "1mm-visual-polish",
      title: "Polish visuel",
      description: "Harmoniser palette, animations et feedback de pièces.",
      impact: 5,
      effort: 5,
      urgency: 2,
      recommended: false,
      reason: "Secondaire tant que le gameplay n'est pas validé.",
    },
  ],
  "le-dernier-souvenir": [
    {
      id: "lds-bible",
      title: "Écrire la bible narrative",
      description: "Arc principal, personnages, ton et structure en 3 actes.",
      impact: 8,
      effort: 6,
      urgency: 2,
      recommended: true,
      reason: "Première brique si le projet redevient actif.",
    },
    {
      id: "lds-visual-id",
      title: "Définir l'identité visuelle",
      description: "Moodboard et direction artistique cohérente.",
      impact: 6,
      effort: 5,
      urgency: 2,
      recommended: false,
      reason: "Après la bible narrative.",
    },
  ],
  "gigi-os": [
    {
      id: "gigi-onboarding",
      title: "Stabiliser l'onboarding",
      description: "Premier run fluide : projets → mission → usage quotidien.",
      impact: 9,
      effort: 5,
      urgency: 8,
      recommended: false,
      reason: "Déjà bien avancé — maintenance continue.",
    },
    {
      id: "gigi-mission-engine",
      title: "Améliorer le moteur de mission",
      description: "Priorisation plus explicable et suggestions par projet.",
      impact: 9,
      effort: 6,
      urgency: 8,
      recommended: true,
      reason: "Renforce la promesse « Sache quoi faire ».",
      suggestedTasks: ["Détail projet", "Missions possibles", "Lien conversation"],
    },
    {
      id: "gigi-controlled-actions",
      title: "Préparer actions contrôlées",
      description: "Dry-run pour actions futures sans exécution réelle.",
      impact: 7,
      effort: 7,
      urgency: 5,
      recommended: false,
      reason: "V1.7+ — après le cœur mission.",
    },
    {
      id: "gigi-project-detail",
      title: "Ajouter détail projet",
      description: "Vue actionnable par projet avec missions possibles.",
      impact: 8,
      effort: 5,
      urgency: 7,
      recommended: false,
      reason: "En cours avec V1.6.",
    },
  ],
};

export function getMissionSeedsForProject(projectId: string): ProjectMissionSuggestion[] {
  const seeds = BY_PROJECT[projectId] ?? getGenericMissions(projectId);
  return seeds.map((s) => ({ ...s, projectId }));
}

function getGenericMissions(projectId: string): MissionSeed[] {
  return [
    {
      id: `${projectId}-next`,
      title: "Avancer la prochaine action",
      description: "Concentre-toi sur l'étape la plus claire du projet.",
      impact: 6,
      effort: 4,
      urgency: 5,
      recommended: true,
      reason: "Action par défaut quand le projet n'a pas de catalogue dédié.",
    },
  ];
}
